sudo: false
language: go
go:
  - 1.7.5
install:
  - make install-dependencies
  - make install-test-dependencies
script:
  - go vet `go list ./... | grep -v vendor`
  - fmtTest=$(go fmt `go list ./... | grep -v vendor` 2>&1); [[ -z $fmtTest ]]
  - make test
