sudo: false
language: go
go:
  - 1.7.5
install:
  - make install-dependencies
  - make install-test-dependencies
script:
  - ! go fmt `go list ./... | grep -v vendor` | read
  - go vet `go list ./... | grep -v vendor`
  - make test
